server:
  port: 8081

spring:
  application:
    name: service-b
  config:
    import: "configserver:"

  cloud:
    config:
      # https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_spring_cloud_config_client
      discovery:
        # The default is false
        enabled: true
        service-id: config-server
      failFast: true
      retry:
        initial-interval: 1000
        max-attempts: 100
        max-interval: 10000
        multiplier: 1.5

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${SPRING_CLOUD_EUREKA_URI:http://localhost:8761/eureka/}