management:

  # Expose default monitoring endpoints
  endpoints:
    web:
      exposure:
        include: "*"

  # Since Spring Boot 2.6 the environment info contributor is disabled by default
  # You have to enable is explicitly.
  info:
    env:
      enabled: true

info:
  application:
    name: ${spring.application.name}

